In [24]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [25]:
df =pd.read_csv(r'Data\clean_bikes.csv')

In [26]:
df

,Unnamed: 0,owner,brand,price,kms_driven,age,power
0,0,1,TVS,35000.0,17654.0,3.0,110.0
1,1,1,Royal Enfield,119900.0,11000.0,4.0,350.0
2,2,1,Triumph,600000.0,110.0,8.0,675.0
3,3,1,TVS,65000.0,16329.0,4.0,180.0
4,4,1,Yamaha,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
7301,9362,1,Hero,25000.0,48587.0,8.0,150.0
7302,9369,1,Bajaj,35000.0,60000.0,9.0,220.0
7303,9370,1,Harley-Davidson,450000.0,3430.0,4.0,750.0
7304,9371,1,Bajaj,139000.0,21300.0,4.0,400.0


In [27]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.isnull().sum()

owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [30]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [31]:
brand_list= df['brand'].unique().tolist()
brand_dict={b:i+1 for i,b in enumerate(brand_list)}
print(brand_dict)

df['brand']=df['brand'].map(brand_dict)

{'TVS': 1, 'Royal Enfield': 2, 'Triumph': 3, 'Yamaha': 4, 'Honda': 5, 'Hero': 6, 'Bajaj': 7, 'Suzuki': 8, 'Benelli': 9, 'KTM': 10, 'Mahindra': 11, 'Kawasaki': 12, 'Ducati': 13, 'Hyosung': 14, 'Harley-Davidson': 15, 'Jawa': 16, 'BMW': 17, 'Indian': 18, 'Rajdoot': 19, 'LML': 20, 'Yezdi': 21, 'MV': 22, 'Ideal': 23}


In [32]:
# brand_dict = {
#     'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
#            'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
#          'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
#           'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
#              'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
#            'Yezdi':21,              'MV':22,           'Ideal':23
#               }

# df['brand']=df['brand'].map(brand_dict)

df

,owner,brand,price,kms_driven,age,power
0,1,1,35000.0,17654.0,3.0,110.0
1,1,2,119900.0,11000.0,4.0,350.0
2,1,3,600000.0,110.0,8.0,675.0
3,1,1,65000.0,16329.0,4.0,180.0
4,1,4,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...
7301,1,6,25000.0,48587.0,8.0,150.0
7302,1,7,35000.0,60000.0,9.0,220.0
7303,1,15,450000.0,3430.0,4.0,750.0
7304,1,7,139000.0,21300.0,4.0,400.0


In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.drop_duplicates()

,owner,brand,price,kms_driven,age,power
0,1,1,35000.0,17654.0,3.0,110.0
1,1,2,119900.0,11000.0,4.0,350.0
2,1,3,600000.0,110.0,8.0,675.0
3,1,1,65000.0,16329.0,4.0,180.0
4,1,4,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...
7301,1,6,25000.0,48587.0,8.0,150.0
7302,1,7,35000.0,60000.0,9.0,220.0
7303,1,15,450000.0,3430.0,4.0,750.0
7304,1,7,139000.0,21300.0,4.0,400.0


In [35]:
x=df.drop(['price'],axis=1)

In [36]:
y= df[['price']]

In [37]:
x

,owner,brand,kms_driven,age,power
0,1,1,17654.0,3.0,110.0
1,1,2,11000.0,4.0,350.0
2,1,3,110.0,8.0,675.0
3,1,1,16329.0,4.0,180.0
4,1,4,10000.0,3.0,150.0
...,...,...,...,...,...
7301,1,6,48587.0,8.0,150.0
7302,1,7,60000.0,9.0,220.0
7303,1,15,3430.0,4.0,750.0
7304,1,7,21300.0,4.0,400.0


In [38]:
y

,price
0,35000.0
1,119900.0
2,600000.0
3,65000.0
4,80000.0
...,...
7301,25000.0
7302,35000.0
7303,450000.0
7304,139000.0


In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [40]:
x_train

,owner,brand,kms_driven,age,power
6302,1,1,12061.0,4.0,180.0
7037,2,7,40000.0,7.0,220.0
640,1,6,28329.0,6.0,110.0
6153,2,7,10000.0,8.0,220.0
1755,1,5,26000.0,8.0,150.0
...,...,...,...,...,...
5191,1,7,15383.0,2.0,100.0
5226,1,8,45263.0,6.0,150.0
5390,1,6,45000.0,6.0,100.0
860,1,4,14836.0,8.0,150.0


In [41]:
x_test

,owner,brand,kms_driven,age,power
7062,1,5,35000.0,9.0,250.0
4553,1,14,9066.0,5.0,250.0
6505,1,6,48000.0,17.0,100.0
1918,1,7,20222.0,5.0,150.0
5227,1,8,27167.0,5.0,150.0
...,...,...,...,...,...
2045,1,5,98971.0,8.0,150.0
527,1,14,2881.0,7.0,250.0
1783,1,2,6517.0,2.0,350.0
5065,1,2,5222.0,5.0,350.0


In [42]:
y_train

,price
6302,65000.0
7037,49000.0
640,32000.0
6153,36000.0
1755,70000.0
...,...
5191,38000.0
5226,62000.0
5390,30000.0
860,40000.0


In [43]:
y_test

,price
7062,125000.0
4553,220000.0
6505,16900.0
1918,58000.0
5227,58000.0
...,...
2045,25000.0
527,140000.0
1783,156000.0
5065,118000.0


In [44]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5844, 5), (1462, 5), (5844, 1), (1462, 1))

# SVM (SVR)

In [45]:
from sklearn.svm import SVR
sv=SVR()
sv.fit(x_train,y_train)


c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,tol,0.001
,C,1.0
,epsilon,0.1
,shrinking,True
,cache_size,200
,verbose,False
,max_iter,-1


In [46]:
pred=sv.predict(x_test)
print(pred)
print('SVR test score:-',sv.score(x_test,y_test))
print('SVR train score:-',sv.score(x_train,y_train))

[53990.22593309 54898.09273564 53714.93508548 ... 54953.11680016
 54976.1473673  55007.82068255]
SVR test score:- -0.05789256698689371
SVR train score:- -0.06164747200042009


# SVM (SVC)

In [47]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)


c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [48]:
pred=sv.predict(x_test)
print(pred)
print('SVC test score:-',sv.score(x_test,y_test))
print('SVC train score:-',sv.score(x_train,y_train))

[35000. 65000. 25000. ... 90000. 90000. 90000.]
SVC test score:- 0.0280437756497948
SVC train score:- 0.03199863107460643


# Linear Regression

In [49]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [50]:
pred=lr.predict(x_test)
print(pred)
print('LinearRegression test score:-',lr.score(x_test,y_test))
print('LinearRegression train score:-',lr.score(x_train,y_train))

[[ 83929.37665134]
 [180558.39832151]
 [-22099.3593951 ]
 ...
 [141514.63936525]
 [131317.32984841]
 [ 10099.13186723]]
LinearRegression test score:- 0.743480827241775
LinearRegression train score:- 0.7116425245703818


In [51]:
from sklearn.linear_model import LogisticRegression
log =LogisticRegression()
log.fit(x_train,y_train)

c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [52]:
pred=log.predict(x_test)
print(pred)
print("LogisticRegression training",log.score(x_train,y_train))
print("LogisticRegression testing",log.score(x_test,y_test))

[25000. 25000. 25000. ... 35000. 35000. 35000.]
LogisticRegression training 0.024640657084188913
LogisticRegression testing 0.0280437756497948


# DecisionTreeClassifier

In [53]:
from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier()
dt.fit(x_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [54]:
pred=dt.predict(x_test)
print(pred)
print('DecisionTreeClassifier test score:-',dt.score(x_test,y_test))
print('DecisionTreeClassifier train score:-',dt.score(x_train,y_train))

[ 80000. 190000.  17200. ... 170000. 139300.  86900.]
DecisionTreeClassifier test score:- 0.03761969904240766
DecisionTreeClassifier train score:- 0.9493497604380561


### with perameter

In [55]:
dt.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [56]:
from sklearn.tree import DecisionTreeClassifier
dt =DecisionTreeClassifier(criterion='entropy', min_samples_split=3, min_samples_leaf=2, random_state=42)
dt.fit(x_train, y_train)



,criterion,'entropy'
,splitter,'best'
,max_depth,None
,min_samples_split,3
,min_samples_leaf,2
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [57]:
pred=dt.predict(x_test)
print(pred)
print('DecisionTreeClassifier test score:-',dt.score(x_test,y_test))
print('DecisionTreeClassifier train score:-',dt.score(x_train,y_train))

[100000. 190000.  15000. ... 129500.  90000.  65000.]
DecisionTreeClassifier test score:- 0.032147742818057455
DecisionTreeClassifier train score:- 0.4710814510609172


# DecisionTreeRegressor

In [58]:
from sklearn.tree import DecisionTreeRegressor
import joblib
dt =DecisionTreeRegressor()
dt.fit(x_train, y_train)

,criterion,'squared_error'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,ccp_alpha,0.0


In [59]:
pred=dt.predict(x_test)
print(pred)
print('DecisionTreeRegressor test score:-',dt.score(x_test,y_test))
print('DecisionTreeRegressor train score:-',dt.score(x_train,y_train))

[ 85000. 155000.  10669. ... 170000. 110000.  63000.]
DecisionTreeRegressor test score:- 0.8550724584730993
DecisionTreeRegressor train score:- 0.9978073030729452


In [60]:
# joblib.dump(dt, 'DecisionTreeRegressor_model.lb')
# print("Model saved successfully!")

In [61]:
# model=joblib.load('DecisionTreeRegressor_model.lb')
# print(model.predict(x_test))

### with perameter

In [62]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(criterion='squared_error',min_samples_split=3,min_samples_leaf=2,random_state=42)
dt.fit(x_train, y_train)


,criterion,'squared_error'
,splitter,'best'
,max_depth,None
,min_samples_split,3
,min_samples_leaf,2
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,ccp_alpha,0.0


In [63]:
pred=dt.predict(x_test)
print(pred)
print("DecisionTreeRegressor Test Score:", dt.score(x_test, y_test))
print("DecisionTreeRegressor Train Score:", dt.score(x_train, y_train))

[ 77700.         204000.          12789.66666667 ... 165000.
 116700.          65200.        ]
DecisionTreeRegressor Test Score: 0.8450540574036833
DecisionTreeRegressor Train Score: 0.9743177859999623


# KNN


In [64]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
knn=KNeighborsRegressor()
knn.fit(x_train, y_train)


,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [65]:
print("KNeighborsRegressor Test Score:", knn.score(x_test, y_test))
print("KNeighborsRegressor Train Score:", knn.score(x_train, y_train))

KNeighborsRegressor Test Score: 0.6676682666067486
KNeighborsRegressor Train Score: 0.7959014087606904


In [66]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
knn=KNeighborsClassifier()
knn.fit(x_train, y_train)

c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [67]:
print("KNeighborsClassifier Test Score:", knn.score(x_test, y_test))
print("KNeighborsClassifier Train Score:", knn.score(x_train, y_train))

KNeighborsClassifier Test Score: 0.01709986320109439
KNeighborsClassifier Train Score: 0.21697467488021902


## RandomForestRegressor

In [68]:
from sklearn.ensemble import RandomForestRegressor 
import joblib
rfr =RandomForestRegressor()
rfr.fit(x_train, y_train)

c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


,n_estimators,100
,criterion,'squared_error'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,1.0
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [69]:
print(' test score:-',rfr.score(x_test,y_test))
print('train score:-',rfr.score(x_train,y_train))

 test score:- 0.881545137284158
train score:- 0.9859850173198422


In [70]:
# joblib.dump(rfr, 'RandomForestRegressor.lb')
print("Model saved successfully!")

Model saved successfully!


## with parameter

In [71]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(criterion='squared_error', min_samples_split=3, min_samples_leaf=2, random_state=42)
rfr.fit(x_train, y_train)


c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


,n_estimators,100
,criterion,'squared_error'
,max_depth,None
,min_samples_split,3
,min_samples_leaf,2
,min_weight_fraction_leaf,0.0
,max_features,1.0
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [72]:
print(' test score:-',rfr.score(x_test,y_test))
print('train score:-',rfr.score(x_train,y_train))

 test score:- 0.880776787745988
train score:- 0.967143049005996


### RandomForestClassifier 

In [73]:
from sklearn.ensemble import RandomForestClassifier 
import joblib
rfc =RandomForestClassifier()
rfc.fit(x_train, y_train)

c:\Users\KRISHAN\Downloads\data science\projects\bike_price_prediction\bike_anand\lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [74]:
print('test score:-',rfc.score(x_test,y_test))
print('train score:-',rfc.score(x_train,y_train))

test score:- 0.03761969904240766
train score:- 0.9493497604380561
